site_name: Raffl.online Docs
site_url: https://docs.raffl.online
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.expand
extra:
  analytics:
    provider: google
    property: G-NHB27Z7BSP
